import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav_bar from './layout/nav_bar'
import Header from './layout/header'
import { Suspense } from 'react'
import Loading from './loading'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" /></head>
      <body className={inter.className}>
        <Nav_bar/>
        <Header/>
        <Suspense fallback={<Loading/>}>
        {children}
        </Suspense>
        
        </body>
    </html>
  )
}
